### ISSUE TITLE
Other improvements

### ISSUE THREAD

**Issue by Cappo66** [WSS-tracking/WSS#98]
- Headshot - the two special groups should have headshot on all the time, at any distance. ; once the player base gets a bit bigger, it'd be a good idea to remove the headshot for everyone without the two special groups, as some people might find the current headshot a bit too powerful. 

- The two special groups should have more guns, as the AK, deagle and knife isn't enough. I'd suggest adding CS, grenades, sniper, tec / uzi...

- Move the classes so they make a bit more sense; here's my order suggestion
Admins; Squads, Police, Desert Storm, Cobra Rebellion, Emergency, Civilians, Gangs, Criminals and the rest of the groups.

**Comment by WSSLidl** [comment]
If you're referring to the armies as special groups; they will get more classes when the playercount is higher. But atm, we don't want people to spawn army all day; thus weapons are limited

Headshot at any distance is OP, since some people will use it to instant kill you while standing 1meter away from you.

I'll see what i can do about the class orders
